# Generated by Django 6.0.1 on 2026-02-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
    ]
