# Generated by Django 6.0.1 on 2026-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0010_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('RETURNED', 'Returned')], default='LOST', max_length=20),
        ),
    ]
